version: "1.0"
info:
  model: int-scaffold
packages:
- name: Ser_TestBranchProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: Arti
services:
- serviceName: project.ser_testbranch.integrations:gcd_branch
  packages:
  - name: Ser_TestBranchProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2076
